repos:
  - repo: local
    hooks:
      - id: gitleaks-native
        name: Gitleaks Secret Scan
        entry: gitleaks
        args: [detect, --source, ., --no-banner]
        language: system
        pass_filenames: false

      - id: eslint-local
        name: ESLint Code Lint
        entry: node_modules/.bin/eslint
        language: system
        pass_filenames: false
        types: [javascript, jsx]
        args: ["src//*.js", "src//*.jsx"]  # or "." for all files in repo

