repos:
  - repo: local
    hooks:
      - id: gitleaks-native
        name: Gitleaks Secret Scan
        entry: gitleaks
        args: [detect, --source, ., --no-banner]
        language: system
        pass_filenames: false

      - id: eslint-local
        name: ESLint Code Lint
        entry: node_modules/.bin/eslint
        language: system
        types: [javascript, jsx]
        args: ["my-portfolio/**/*.js,cjs"]  # or "." for all files in repo

