name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read
  security-events: write

jobs:

  pipeline:
    name: Run Pipeline
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        task:
          - build
          - lint
          - test
          - codeql
          - snyk
          - checkov
          - gitleaks
          - trivy

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Setup Node
        
        if: matrix.task == 'build' || matrix.task == 'lint' || matrix.task == 'test' || matrix.task == 'snyk'
        uses: actions/setup-node@v4
        with:
          node-version: 20
          

      - name: Install
        if: matrix.task == 'build' || matrix.task == 'lint' || matrix.task == 'test' || matrix.task == 'snyk'
        run: npm install
        working-directory: frontend

      - name: Build
        if: matrix.task == 'build'
        run: npm run build
        working-directory: frontend

      - name: Lint
        if: matrix.task == 'lint'
        run: npm run lint
        working-directory: frontend

      - name: Test
        if: matrix.task == 'test'
        run: npm test
        working-directory: frontend

      - name: CodeQL Init
        if: matrix.task == 'codeql'
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: CodeQL Analyze
        if: matrix.task == 'codeql'
        uses: github/codeql-action/analyze@v3

      - name: Snyk Scan
        if: matrix.task == 'snyk'
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --file=frontend/package.json

          

      - name: Run Checkov
        if: matrix.task == 'checkov'
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ./Terraform
          soft_fail: false

      - name: Install Gitleaks
        if: matrix.task == 'gitleaks'
        run: |
          git ls-files | grep tfstate
          git rev-list --count HEAD
          wget -q https://github.com/gitleaks/gitleaks/releases/download/v8.18.4/gitleaks_8.18.4_linux_x64.tar.gz
          tar -xzf gitleaks_8.18.4_linux_x64.tar.gz
          mv gitleaks /usr/local/bin/gitleaks
          chmod +x /usr/local/bin/gitleaks

      - name: Run Gitleaks
        if: matrix.task == 'gitleaks'
        run: gitleaks detect --source . --no-banner --no-git --report-format sarif --report-path gitleaks-results.sarif

      - name: Upload Gitleaks SARIF
        if: matrix.task == 'gitleaks'
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: gitleaks-results.sarif

      - name: Install Trivy
        if: matrix.task == 'trivy'
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

     
        
      - name: Biuld image for Trivy 
        if: matrix.task == 'trivy'
        run: |
          docker build -t ${{ github.repository }}:trivy-${{ github.run_id}} -f frontend/Dockerfile .

      - name: Trivy image scan
        if: matrix.task == 'trivy'
        run: trivy image --format sarif --severity HIGH,CRITICAL --exit-code 1 --output trivy-image-results.sarif ${{ github.repository }}:trivy-${{ github.run_id}}
        
     


      - name: Upload Trivy SARIF
        if: matrix.task == 'trivy'
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-image-results.sarif

  terraform_deploy:
    name: Terraform Deploy
    runs-on: ubuntu-latest
    needs: pipeline
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        working-directory: Terraform
        run: terraform init
      - name: Terraform Validate
        working-directory: Terraform
        run: terraform validate
      - name: Terraform Plan
        working-directory: Terraform
        run: terraform plan
      - name: Terraform Apply
        working-directory: Terraform
        run: terraform apply -auto-approve

  upload_site:
    name: Upload Site to S3
    runs-on: ubuntu-latest
    needs: terraform_deploy
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm install
        working-directory: frontend
      - name: Build frontend
        run: npm run build
        working-directory: frontend

      - name: upload to S3
        run: aws s3 sync frontend/dist s3://$S3_BUCKET_NAME --delete
      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
      

